### ISSUE TITLE
記事のデザイン案

### ISSUE THREAD

**Issue by 0V** [Atis9/nyantech.com#53]
**機能リクエストは何かしらの問題に関連するものか？**
記事の読みやすさ。

**希望の解決策についての説明**
- フォントサイズを大きくする。
  - かつ、フォントサイズの指定を rem 指定にする。
- 記事の背景に色を付けて、テキストエリアとそれ以外を明確に区別する。

**色付けのイメージ**
![image](https://user-images.githubusercontent.com/7000978/166137175-e3c6d45d-3d1a-4606-b7d6-302cee856c72.png)

**Comment by Atis9** [comment]
フォントサイズを大きくするのはアリだと思っています。
また、テキストエリアの区切りに関しては `border` などを利用して GitHub ライク（この Issue ページのよう）なデザインにすることを検討しています。
ひとまず PR を作ってデザインを作ってみるので意見をください。

**Comment by Atis9** [comment]
とりあえず作ってみた。
どうですか。
https://nyantech-com-git-atis9-53-fix-design-atis9.vercel.app/

**Comment by Atis9** [comment]
ひとまず対応しました。
文字サイズは要検討。

**Comment by Atis9** [comment]
文字サイズはここらへんをオーバライドすれば対応できそう。
[Typography \| Primer CSS](https://primer.style/css/support/typography)

**Comment by Atis9** [comment]
記事一覧の表示も修正した。（flex box の活用が難しい）

**Comment by Atis9** [comment]
そもそもフォントを指定していないことに気づいた。

**Comment by Atis9** [comment]
@0V 全体に手を入れちゃったけど、デザインとして見やすくなったと思います。どうです？

**Comment by 0V** [comment]
いま屋外なのでスマホからのチェックなんですが、自分的には良い感じです

**Comment by 0V** [comment]
PCからも見たんですが、僕の環境だと英字がやけに大きく感じます

![image](https://user-images.githubusercontent.com/7000978/166264406-24bf1832-89ca-4df5-8d2f-8ca8665501c7.png)

**Comment by Atis9** [comment]
> PCからも見たんですが、僕の環境だと英字がやけに大きく感じます

それは多分フォントの特性だと思います。
[BIZ UDPGothic \- Google Fonts](https://fonts.google.com/specimen/BIZ+UDPGothic)
でも確かにちょっとバランスが悪い感じはする。

**Comment by Atis9** [comment]
あとは私が Word の前後にスペースを入れる派閥なので、より大きく見えるのはあるかも。
